export const PRELOAD_FORM_META = 'PRELOAD_FORM_META';
export const UNLOAD_FORM_META = 'UNLOAD_FORM_META';
export const GET_UNLOAD_FORM_META = 'GET_UNLOAD_FORM_META';
export const FORM_META_REQUESTED = 'FORM_META_REQUESTED';
export const FORM_META_SUCCESSED = 'FORM_META_SUCCESSED';
export const FORM_META_FAILED = 'FORM_META_FAILED';

export const SET_FORM_DATA_PENDING = 'SET_FORM_DATA__PENDING';
export const SET_FORM_DATA_SUCCESSED = 'SET_FORM_DATA_SUCCESSED';
export const SET_FORM_DATA_FAILED = 'SET_FORM_DATA_FAILED';
